spring.application.name=versioned-kv-store
spring.datasource.url=jdbc:postgresql://postgres:${POSTGRES_PORT:5432}/${POSTGRES_DB:kvdb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
